openapi: 3.0.0
info:
  title: BoTreasure API
  description: BoTreasureに関するAPI仕様書です。
  version: 1.0.0
paths:
  /api/user/{userId}:
    get:
      tags:
          - User
      summary: Get user by ID
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    post:
      tags:
          - User
      summary: Create a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    delete:
      tags:
          - User
      summary: Delete user by ID
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
      responses:
        '204':
          description: User deleted successfully
  /api/team/{teamId}:
    get:
      tags:
          - Team
      summary: Get team by ID
      parameters:
        - in: path
          name: teamId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Team'
    post:
      tags:
          - Team
      summary: Create a new team
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Team'
      responses:
        '201':
          description: Team created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Team'
    delete:
      tags:
          - Team
      summary: Delete team by ID
      parameters:
        - in: path
          name: teamId
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Team deleted successfully
    patch:
      tags:
          - Team
      summary: Update team by ID
      parameters:
        - in: path
          name: teamId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Team'
      responses:
        '200':
          description: Team updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Team'
  /api/teams:
      get:
        summary: Get all teams
        responses:
          '200':
            description: Successful operation
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/Team'
components:
  schemas:
    User:
      type: object
      properties:
        userId:
          type: string
        name:
          type: string
        status:
          type: string
          enum: [host, guest, owner, seeker]
          nullable: true
        teamId:
          type: string
          nullable: true
        role:
          type: string
          enum: [host, guest]
          nullable: true
        gameType:
          type: string
          enum: [owner, seeker]
          nullable: true
    Team:
      type: object
      properties:
        teamId:
          type: string
        hostId:
          type: string
        name:
          type: string
        playerCount:
          type: integer
          nullable: true
        ownerCount:
          type: integer
          nullable: true
        keyword:
          type: string
          nullable: true
