/**
 * BoTreasure API
 * BoTreasureに関するAPI仕様書です。
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import * as api from "./api"
import { Configuration } from "./configuration"

const config: Configuration = {}

describe("DefaultApi", () => {
  let instance: api.DefaultApi
  beforeEach(function() {
    instance = new api.DefaultApi(config)
  });

  test("apiGameTeamIdGet", () => {
    return expect(instance.apiGameTeamIdGet({})).resolves.toBe(null)
  })
  test("apiScannerStatusUserIdGet", () => {
    return expect(instance.apiScannerStatusUserIdGet({})).resolves.toBe(null)
  })
  test("apiTeamBuildingPost", () => {
    const body: api.ApiTeambuildingBody = undefined
    return expect(instance.apiTeamBuildingPost(body, {})).resolves.toBe(null)
  })
  test("apiTeamJoiningPost", () => {
    const body: api.ApiTeamjoiningBody = undefined
    return expect(instance.apiTeamJoiningPost(body, {})).resolves.toBe(null)
  })
  test("apiTeamTeamIdDelete", () => {
    const teamId: string = "teamId_example"
    return expect(instance.apiTeamTeamIdDelete(teamId, {})).resolves.toBe(null)
  })
  test("apiTeamTeamIdGet", () => {
    const teamId: string = "teamId_example"
    return expect(instance.apiTeamTeamIdGet(teamId, {})).resolves.toBe(null)
  })
  test("apiTeamsGet", () => {
    return expect(instance.apiTeamsGet({})).resolves.toBe(null)
  })
  test("apiUserUserIdGet", () => {
    const userId: string = "userId_example"
    return expect(instance.apiUserUserIdGet(userId, {})).resolves.toBe(null)
  })
})

describe("QRApi", () => {
  let instance: api.QRApi
  beforeEach(function() {
    instance = new api.QRApi(config)
  });

  test("apiQrScanPost", () => {
    const body: api.ApiQrscanBody = undefined
    return expect(instance.apiQrScanPost(body, {})).resolves.toBe(null)
  })
})

describe("TreasureQR_Api", () => {
  let instance: api.TreasureQR_Api
  beforeEach(function() {
    instance = new api.TreasureQR_Api(config)
  });

  test("apiCreateQrPost", () => {
    const body: api.ApiCreateqrBody = undefined
    return expect(instance.apiCreateQrPost(body, {})).resolves.toBe(null)
  })
})

describe("_Api", () => {
  let instance: api._Api
  beforeEach(function() {
    instance = new api._Api(config)
  });

  test("apiBeaconPost", () => {
    const body: api.ApiBeaconBody = undefined
    return expect(instance.apiBeaconPost(body, {})).resolves.toBe(null)
  })
  test("apiCreateHintPost", () => {
    const body: api.ApiCreatehintBody = undefined
    return expect(instance.apiCreateHintPost(body, {})).resolves.toBe(null)
  })
  test("apiSaveHintPost", () => {
    const body: api.SaveHintBody = undefined
    return expect(instance.apiSaveHintPost(body, {})).resolves.toBe(null)
  })
  test("apiSchedulePost", () => {
    const body: api.ApiScheduleBody = undefined
    return expect(instance.apiSchedulePost(body, {})).resolves.toBe(null)
  })
})

