/**
 * BoTreasure API
 * BoTreasureに関するAPI仕様書です。
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import * as api from "./api"
import { Configuration } from "./configuration"

const config: Configuration = {}

describe("DefaultApi", () => {
  let instance: api.DefaultApi
  beforeEach(function() {
    instance = new api.DefaultApi(config)
  });

  test("apiSchedulePost", () => {
    const body: api.ApiScheduleBody = undefined
    return expect(instance.apiSchedulePost(body, {})).resolves.toBe(null)
  })
  test("apiTeamBuildingPost", () => {
    const body: api.ApiTeambuildingBody = undefined
    return expect(instance.apiTeamBuildingPost(body, {})).resolves.toBe(null)
  })
  test("apiTeamJoiningPost", () => {
    const body: api.ApiTeamjoiningBody = undefined
    return expect(instance.apiTeamJoiningPost(body, {})).resolves.toBe(null)
  })
})

describe("GameApi", () => {
  let instance: api.GameApi
  beforeEach(function() {
    instance = new api.GameApi(config)
  });

  test("apiGameTeamIdGet", () => {
    return expect(instance.apiGameTeamIdGet({})).resolves.toBe(null)
  })
})

describe("QRApi", () => {
  let instance: api.QRApi
  beforeEach(function() {
    instance = new api.QRApi(config)
  });

  test("apiQrScanPost", () => {
    const body: api.ApiQrscanBody = undefined
    return expect(instance.apiQrScanPost(body, {})).resolves.toBe(null)
  })
})

describe("TeamApi", () => {
  let instance: api.TeamApi
  beforeEach(function() {
    instance = new api.TeamApi(config)
  });

  test("apiTeamTeamIdDelete", () => {
    const teamId: string = "teamId_example"
    return expect(instance.apiTeamTeamIdDelete(teamId, {})).resolves.toBe(null)
  })
  test("apiTeamTeamIdGet", () => {
    const teamId: string = "teamId_example"
    return expect(instance.apiTeamTeamIdGet(teamId, {})).resolves.toBe(null)
  })
  test("apiTeamTeamIdPatch", () => {
    const body: api.Team = undefined
    const teamId: string = "teamId_example"
    return expect(instance.apiTeamTeamIdPatch(body, teamId, {})).resolves.toBe(null)
  })
})

describe("TeamsApi", () => {
  let instance: api.TeamsApi
  beforeEach(function() {
    instance = new api.TeamsApi(config)
  });

  test("apiTeamsGet", () => {
    return expect(instance.apiTeamsGet({})).resolves.toBe(null)
  })
})

describe("UserApi", () => {
  let instance: api.UserApi
  beforeEach(function() {
    instance = new api.UserApi(config)
  });

  test("apiUserUserIdGet", () => {
    const userId: string = "userId_example"
    return expect(instance.apiUserUserIdGet(userId, {})).resolves.toBe(null)
  })
})

