import type { Metadata } from "next";
import "./globals.css";
import { LiffProvider } from "@/components/LiffProvider";
import { Noto_Sans_JP } from "next/font/google";
import clsx from "clsx";

const noto = Noto_Sans_JP({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-noto-sans-jp",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" className={clsx(noto.className, "font-sans")}>
      <body>
        <LiffProvider liffId={process.env.NEXT_PUBLIC_LIFF_ID || ""}>
          {children}
        </LiffProvider>
      </body>
    </html>
  );
}
