name: Repository Dispatch Workflow
on:
  repository_dispatch:
    types: [test_result]

jobs:
  run_if_failure:
    if: ${{ !github.event.client_payload.passed }}
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./typst
    steps:
      - uses: actions/checkout@v4
      - env:
          MESSAGE: ${{ github.event.client_payload.message }}
        run: echo $MESSAGE
      - name: pwd
        run: pwd
      - name: ls
        run: ls
      - name: Install Typst
        run: brew install typst
      - name: Typst Compile
        run: typst compile main.typ out.png
      - name: ls
        run: ls